### ISSUE TITLE
Adicionar animação ao modal

### ISSUE THREAD

**Issue by jessescn** [Guardians-DSC/horarios-ufcg#101]
Acho que ficaria bacana adicionar algum efeito de transição ao abrir o modal, algo como tem na página dos cursos do analytics.

**Comment by ArthurFerrao** [comment]
Obrigado pela ideia, isso seria legal mesmo. Se quiser tentar fazer, pode ficar a vontade para abrir PR.

**Comment by jessescn** [comment]
Opa, quero sim, considere feito ;)

**Comment by ArthurFerrao** [comment]
Todo seu
