### ISSUE TITLE
Problema com seleção

### ISSUE THREAD

**Issue by RaylaMedeiros** [Guardians-DSC/horarios-ufcg#103]
Quando se passa o mouse por uma disciplina, o hover é feito nos dois horários da disciplina, porém, quando se clica na disciplina a marcação é feita apenas em um dos horários

**Comment by lucaspontoexe** [comment]
Acabei de testar, e acontece um problema parecido com a disciplina `irc/lirc` (Interconexão de Redes de Computadores/Laboratório de Interconexão de Redes de Computadores)

Além de não selecionar as disciplinas correspondentes, um erro é disparado no console toda vez que se passa o mouse por cima dela.

**Comment by joaobb** [comment]
O erro é aparentemente causado pela presença da barra "/" no nome da disciplina em contato com a função de document.querySelectorAll()

**Comment by jadsonluan** [comment]
Corrigido em #107
