### ISSUE TITLE
VueX

### ISSUE THREAD

**Issue by lucaspontoexe** [Guardians-DSC/horarios-ufcg#105]
Vocês pretendem usar vuex nesse projeto? Um store global pode ajudar bastante a tornar o código mais limpo (não vai precisar de `querySelector`, nem manipulação de DOM) - vi que tem um branch de testes

**Comment by douglaslimaxx** [comment]
Olá @lucaspontoexe muito obrigado pela sugestão
Bem, nós não conhecemos vuex o bastante para usá-lo. Mas como ele ajudaria no nosso projeto? 
Se valer a pena nós podemos usá-lo sim.

**Comment by ArthurFerrao** [comment]
A branch de teste foi exatamente pra ver essa possibilidade e realmente achei que deixou mais limpo (por não precisar manipular DOM). E acho que ajudaria com outras funcionalidades como a pesquisa e o filtro.

**Comment by lucaspontoexe** [comment]
Bingo! Era isso que eu ia falar, mas o texto ficou meio longo 😂 
Inclusive, o código consegue ficar mais declarativo e intuitivo

**Comment by danielmitre** [comment]
Estava buscando exatamente por isso pra implementar #77 e #110. O que falta pra branch de testes entrar pra master?

**Comment by ArthurFerrao** [comment]
Até esse final de semana a gente vai discutir sobre isso, estávamos estudando outras formas de fazer isso e estudando mais sobre o vuex. Então é bom não fazer ainda essas issues.

**Comment by ArthurFerrao** [comment]
Mas quando tiver tudo certo a gente avisa aqui.
