### ISSUE TITLE
Mostrar conflitos no hover/click

### ISSUE THREAD

**Issue by thayannevls** [Guardians-DSC/horarios-ufcg#110]
Achei muito legal a feature de marcar a disciplina! Uma coisa que pensei foi, caso dê conflito com uma que já marquei ao dar hover/click, o quadrado horário ficaria com outra cor, não precisa ser gritante, pode ser algo sútil apenas para fins de visualização.

Exemplo: 
<img width="1680" alt="Screen Shot 2019-10-30 at 00 27 23" src="https://user-images.githubusercontent.com/6867958/67826740-54784d80-faac-11e9-961a-538f20b2b281.png">

Nesse caso ai eu marquei *fmcc1*, e passei hover no de *compiladores* dando conflito no horário da terça. O quadrado da terça poderia ter alguma mudança sútil pra simbolizar o conflito.

Acho algo legal e possível fazer só com css e algumas manipulações de variável 👀

**Comment by danielmitre** [comment]
Acho que consigo fazer essa. O que vocês acham de desmarcar as que deram conflito em vez de só mudar a aparência?

Btw, fiz um outro exemplo de cores a serem utilizadas nesse caso do conflito:

![image](https://user-images.githubusercontent.com/25506375/67916082-5ce78b80-fb73-11e9-9403-16a04cb79c67.png)

**Comment by danielmitre** [comment]
Vi que o vuex talvez vá entrar na parada, o que deve afetar diretamente essa lógica. Espero a mudança ou faço com querySelector mesmo?

**Comment by ArthurFerrao** [comment]
@danielmitre é melhor esperar a mudança pois a implementação em query provavelmente seria substituída por algo com vuex.
