### ISSUE TITLE
Evidenciar os horários de disciplina

### ISSUE THREAD

**Issue by douglaslimaxx** [Guardians-DSC/horarios-ufcg#21]
Ao encontrar uma disciplina no horário o usuário não sabe onde está o outro e com isso acaba tendo de fazer outra busca. A ideia é evidenciar os horários de uma disciplina ao passar o mouse nela. Eu só não sei como seria essa evidenciação e queria sugestões.

**Comment by RaylaMedeiros** [comment]
Acho que seria colocar uma cor mais forte ou algo do tipo

**Comment by thayannevls** [comment]
Adicionar um efeito de hover é uma boa, mas também acho que seria necessário dar a opção de deixar evidenciado por um maior tempo, talvez também de ter a opção de ao clicar muda de cor e fica marcado, fazendo com que o usuário não perca de vista

**Comment by ArthurFerrao** [comment]
Acho q aplicaria o efeito normal de hover só que em ambos, a mesma coisa para quando clicasse ambos ficariam marcados.

**Comment by jadsonluan** [comment]
Já foi resolvido!
