### ISSUE TITLE
Implementar possibilidade de fechar janela de detalhes apenas clicando fora dela

### ISSUE THREAD

**Issue by jadsonluan** [Guardians-DSC/horarios-ufcg#63]
Seria interessante se quando clicarmos numa disciplina e os detalhes aparecerem, invés de fechá-la apenas clicando no "X" também ser possível fechar clicando fora da janela.

**Comment by carlan** [comment]
Tenho uma ideia de como resolver isso. Posso?

**Comment by jadsonluan** [comment]
Pode sim, @carlan ! Obrigado pelo apoio. :ghost:
