### ISSUE TITLE
Adicionar Service Worker e Manifest.json

### ISSUE THREAD

**Issue by thayannevls** [Guardians-DSC/horarios-ufcg#64]
Um [service worker](https://developers.google.com/web/fundamentals/primers/service-workers) é um script que seu navegador executa em segundo plano, separado da página da Web.

Podemos usar ele para inúmeras funcionalidades, e ainda sim ele é bem simples. Acho que das features que ele oferece, vocês poderiam utilizar:

- Interceptar requisições e cachear essas requisições, assim o usuário vai carregar o conteúdo muito mais rápido depois da primeira visita
- Permitir a pessoa ver o conteúdo offline, isso é muito útil pra quem tem a internet muito ruim ou tá usando algo como 3G
- Melhoria de carregamento e perfomance
- O site de vocês ser instalável pelo browser e ser acessado pela home screen, tanto desktop como mobile.

Primeiro passo seria criar um service worker simples, também aconselho adicionar um [manifest.json](https://developers.google.com/web/fundamentals/web-app-manifest) e também workbox pra cachear imagens já, e ai é só implementando as coisas aos pouco.

Aqui um [exemplo](https://github.com/OpenDevUFCG/opendevufcg.org/blob/master/docs/service-worker.js)

**Comment by thayannevls** [comment]
Se vocês gostarem da ideia, queria fazer essa issue o/ ou ajudar :p

**Comment by ArthurFerrao** [comment]
Pode fazer sim. Toda sua.
