### ISSUE TITLE
Implementar possibilidade de fechar janela de detalhes apertando ESC

### ISSUE THREAD

**Issue by jadsonluan** [Guardians-DSC/horarios-ufcg#65]
Descrição semelhante a da issue #63

**Comment by breno-pereira** [comment]
Posso pegar essa?

**Comment by jadsonluan** [comment]
Pode sim, @bruno-meneses . Vai em frente! :rocket:

**Comment by joaobb** [comment]
Tá meio parado, então posso pegar essa?

**Comment by jadsonluan** [comment]
Resolvido na PR #80 pelo @joaobb
