### ISSUE TITLE
Loading dos horarios

### ISSUE THREAD

**Issue by fanny** [Guardians-DSC/horarios-ufcg#67]
Primeiramente, parabéns pessoal! Ficou íncrivel o trabalho de voces, apenas uma coisa que pensei que seria legal implementarem. 

Durante o primeiro carregamento da pagina, os horarios levam um tempinho pra carregarem, acho que seria legal incluir um gif de carregamento, pro usuario n achar que é bug e esperar que algo ainda seja exibido.

**Comment by RaylaMedeiros** [comment]
Obrigada @fanny , realmente seria muito interessante ter essa animação pra o usuário saber que está carregando algo. Acho que chegamos a discutir isso em algum ponto e acabamos deixando de lado, mas vamos sim ver como implementar isso, obrigada pela sugestão.

**Comment by carlan** [comment]
Posso dar uma olhada nessa?

**Comment by ArthurFerrao** [comment]
Pode sim @carlan.
