### ISSUE TITLE
Quando clicar em uma turma, evidenciar os outros horários relacionados com ela

### ISSUE THREAD

**Issue by jadsonluan** [Guardians-DSC/horarios-ufcg#75]
Seria interessante implementar uma funcionalidade que quando clicarmos em uma disciplina/turma (exemplo: loac-t1) ela evidencie na tabela todos os horários dessa disciplina. 

Atualmente temos que selecionar clicando nelas individualmente.

![image](https://user-images.githubusercontent.com/13488025/66858167-1b45c680-ef5f-11e9-89ce-7220b42fea61.png)

**Comment by joaobb** [comment]
Consegui fazer funcionar na PR #88, mas o código não está muito abonitado.

**Comment by jadsonluan** [comment]
Muito obrigado, @joaobb ! :heart:

Resolvido na PR #88

**Comment by felipemarinho97** [comment]
Duplicado de #78 ?

**Comment by jadsonluan** [comment]
São funcionalidades diferentes, @felipemarinho97 . A #78 é um *hover* para as disciplinas semelhantes, já esse era com cliques
