### ISSUE TITLE
Implementar barra de pesquisa com sugestões ao digitar

### ISSUE THREAD

**Issue by ArthurFerrao** [Guardians-DSC/horarios-ufcg#77]
Ao clicar no símbolo de pesquisa, que está na navbar, apareça o input de pesquisa e que, ao digitar o nome da disciplina, sejam dadas sugestões de disciplinas assim como mostrado abaixo. 
![image](https://user-images.githubusercontent.com/15989443/67135783-ec944e00-f1f3-11e9-99b9-44c17d69ccc7.png)

**Comment by ArthurFerrao** [comment]
Essa issue depende da discussão na issue #105

**Comment by AntonioNtV** [comment]
Issue concluida na PR #120
