### ISSUE TITLE
Ao passar o mouse em um card de discplina também marcar seu correspondente

### ISSUE THREAD

**Issue by ArthurFerrao** [Guardians-DSC/horarios-ufcg#78]
Atualmente, quando passamos o mouse em uma disciplina, só o card em hover fica selecionado. Na figura abaixo, so-t1 esta com seleção de hover na segunda-feira de 8h, mas seu horário correspondente na quarta-feira de 10h não ficou marcado. O comportamento esperado é que, ao passar o mouse em um dos dois cards, ambos os horários da disciplina sejam selecionados.

![image](https://user-images.githubusercontent.com/15989443/67137242-5c143880-f208-11e9-893a-f67bf61e5ad2.png)

**Comment by andersonclemente** [comment]
Estou tentanto resolver :smile:
