### ISSUE TITLE
Marcar disciplinas utilizando a barra de pesquisa

### ISSUE THREAD

**Issue by ArthurFerrao** [Guardians-DSC/horarios-ufcg#79]
Essa issue depende que a issue #77 seja implementada. 

Ao digitar o nome da disciplina na barra de pesquisa, é esperado que a primeira disciplina que aparece como sugestão seja marcada ao pressionar enter. Depois que a disciplina é marcada, espera-se que a barra de pesquisa fique em branco novamente.

**Comment by ArthurFerrao** [comment]
Essa issue depende da discussão na issue #105

**Comment by AntonioNtV** [comment]
Issue resolvida na PR #120
