### ISSUE TITLE
Criação de componente e estrutura para o filtro

### ISSUE THREAD

**Issue by ArthurFerrao** [Guardians-DSC/horarios-ufcg#81]
Criação do componente filtro com estrutura mostrada abaixo. Todos iniciam selecionados(em roxo) e ao clicar remove a seleção(fica em cinza).
![image](https://user-images.githubusercontent.com/15989443/67136894-bfe83280-f203-11e9-947f-42ea05fa4605.png)

**Comment by lucaspontoexe** [comment]
Oi! tô começando a trabalhar nisso 
![image](https://user-images.githubusercontent.com/25611847/67610509-adbd4580-f769-11e9-833d-5eaa5bf30afe.png)

**Comment by ArthurFerrao** [comment]
Vai fundo, toda sua :)

**Comment by lucaspontoexe** [comment]
![image](https://user-images.githubusercontent.com/25611847/67994354-9677cf80-fc23-11e9-939c-fa0ada9470d0.png)
Um progress report rapidinho
Acredito que ficaria melhor preencher o botão que está selecionado em vez de mudar a cor da borda, para melhorar a visibilidade

**Comment by ArthurFerrao** [comment]
Ola @lucaspontoexe
Nosso medo era que a cor ficasse muito forte pois toda a página tem tons dessa cor. Seria interessante tentar com a borda mais grossa e a letra com a cor. Mas se mesmo assim não ficar bom, pode fazer preenchendo o fundo sim.
