### ISSUE TITLE
Inverter função dos cliques do mouse

### ISSUE THREAD

**Issue by ArthurFerrao** [Guardians-DSC/horarios-ufcg#83]
Atualmente estamos selecionando a cadeira com o botão direito e abrindo o modal de detalhes com o botão esquerdo. Isso deve ser invertido de modo que o botão esquerdo do mouse marque a cadeira e o direito abra o modal de detalhes.

**Comment by joaobb** [comment]
Posso pegar essa?

**Comment by jadsonluan** [comment]
Resolvido na PR #80   do @joaobb
