### ISSUE TITLE
Colapsar e expandir linhas da tabela de horários

### ISSUE THREAD

**Issue by ArthurFerrao** [Guardians-DSC/horarios-ufcg#86]
Ao clicar na hora, no canto esquerdo da tabela, seria interessante que toda a linha colapsasse sumindo todas as cadeiras dentro dela, e com outro clique se expandisse voltando a aparecer as cadeiras.

**Comment by breno-pereira** [comment]
@ArthurFerrao 
Acabei de abrir um PR corrigindo essa issue
