### ISSUE TITLE
Adiciona o campo nome da disciplina ao modal (detalhes)

### ISSUE THREAD

**Issue by jadsonluan** [Guardians-DSC/horarios-ufcg#94]
Seria interessante o modal de detalhes da disciplina possuir também o campo nome da disciplina (basta chamá-lo de nome). O arquivo que o componente Modal está é [este](https://github.com/Guardians-DSC/horarios-ufcg/blob/master/src/components/Modal.vue). E o campo do objeto **aula** que possui o nome da disciplina é chamado de **nome.**

Atualmente o modal se encontra dessa forma:
![image](https://user-images.githubusercontent.com/13488025/67160947-223c5280-f32c-11e9-970f-304f3924ecf4.png)

**Comment by marianasn** [comment]
Peguei pra fazer ;)

**Comment by jadsonluan** [comment]
Obrigado, @marianasn :heart: :heart_eyes:
