### ISSUE TITLE
Mudar endpoints usados para consulta de horários

### ISSUE THREAD

**Issue by jadsonluan** [Guardians-DSC/horarios-ufcg#98]
Atualmente os endpoints usados são da forma /horarios/:dia/:hora, seria interessante migrar para o formato usando query strings. 

### Exemplo
**Atual (route param):** /horarios/sexta/8
**Novo (query string):** /horarios?dia=sexta&hora=8

O arquivo que deve ser modificado é [esse](https://github.com/Guardians-DSC/horarios-ufcg/blob/master/src/components/Horario.vue).

**Comment by lucaspontoexe** [comment]
Todas as rotas vão começar com `/horarios`?

**Comment by jadsonluan** [comment]
Basicamente, as outras rotas vão ser excluídas e só vai ficar a /horarios mesmo. Os filtros vão ser por meio de query strings (que já estão implementados)
